In [14]:
import pandas as pd
import shapely.wkt
import geopandas as gpd

In [16]:
df = pd.read_csv('data/island_data/island-polygon.csv', sep='\t')
gdf = gpd.GeoDataFrame(df, geometry=df['WKT'].apply(shapely.wkt.loads))
gdf

,WKT,NAME,NAME_EN,TYPE,OSM_TYPE,OSM_ID,geometry
0,"MULTIPOLYGON (((73.5316984 4.2191525,73.531511...",ހުޅުލެ,Hulhulé,multipolygon,relation,6615241,"MULTIPOLYGON (((73.5317 4.21915, 73.53151 4.21..."
1,"MULTIPOLYGON (((73.5389368 4.2233084,73.538757...",ހުޅުމާލެ,Hulhumalé,multipolygon,relation,6615242,"MULTIPOLYGON (((73.53894 4.22331, 73.53876 4.2..."
2,"MULTIPOLYGON (((73.5208758 0.3458508,73.509484...",NaN,NaN,multipolygon,relation,7114115,"MULTIPOLYGON (((73.52088 0.34585, 73.50948 0.3..."
3,"MULTIPOLYGON (((73.4881732 3.9415482,73.488275...",Maafushi,NaN,multipolygon,relation,9328389,"MULTIPOLYGON (((73.48817 3.94155, 73.48828 3.9..."
4,"MULTIPOLYGON (((73.5681599 4.6268697,73.568326...",Patina Maldives,NaN,multipolygon,relation,12137584,"MULTIPOLYGON (((73.56816 4.62687, 73.56833 4.6..."
...,...,...,...,...,...,...,...
78,"MULTIPOLYGON (((73.1274905 -0.6777047,73.12790...",Maradhoo,NaN,NaN,way,1286329537,"MULTIPOLYGON (((73.12749 -0.6777, 73.1279 -0.6..."
79,"MULTIPOLYGON (((73.0788459 -0.5834215,73.07890...",NaN,NaN,NaN,way,1286329563,"MULTIPOLYGON (((73.07885 -0.58342, 73.07891 -0..."
80,"MULTIPOLYGON (((72.8450615 3.4756664,72.844901...",Maamigili,NaN,NaN,way,1319728540,"MULTIPOLYGON (((72.84506 3.47567, 72.8449 3.47..."
81,"MULTIPOLYGON (((73.4091682 4.1959764,73.408992...",Giraavaru Falhu,NaN,NaN,way,1327249492,"MULTIPOLYGON (((73.40917 4.19598, 73.40899 4.1..."
82,"MULTIPOLYGON (((73.5082642 0.3386633,73.507796...",މާވާރުލު,NaN,NaN,way,1327500347,"MULTIPOLYGON (((73.50826 0.33866, 73.5078 0.33..."